server:
  port: 8080
  servlet:
    context-path: /
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  type-aliases-package: cn.neusoft.po,cn.neusoft.vo,cn.neusoft.query
  mapper-locations: classpath:cn/neusoft/mapper/*Mapper.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/elmdb
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    cn.neusoft: trace